services:
  flyway:
    image: flyway/flyway:10
    command: migrate
    volumes:
      - ./sql/migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://host.docker.internal:5433/fantasy_snooker
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: password
      FLYWAY_CONNECT_RETRIES: 10
      FLYWAY_BASELINE_ON_MIGRATE: "true"
      FLYWAY_BASELINE_VERSION: "0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
