[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "football-etl"
version = "0.1.0"
dependencies = [
    "requests==2.32.5",
    "psycopg2-binary",
    "python-dotenv",
    "dagster",
    "dagster-webserver",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.dagster]
module_name = "pipeline"
