TRUNCATE
    fact.match_event,
    fact.match_lineup,
    fact.match_manager,
    fact.player_season,
    dim.match,
    dim.player,
    dim.manager,
    dim.club,
    dim.season,
    dim.competition,
    raw.api_response
CASCADE;
